window:
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000
  multiplier: 3

background_opacity: 0.75

font:
  normal:
    family: JetBrains Mono Nerd Font
    style: Medium
  bold: 
    family: JetBrains Mono Nerd Font
    style: Bold
  italic:
    family: JetBrains Mono Nerd Font
    style: MediumItalic
  bold_italic:
    family: JetBrains Mono Nerd Font
    style: BoldItalic
  size: 7

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: "#11121D"
    foreground: "#a9b1d6"
  normal:
    black: "#32344a"
    red: "#f7768e"
    green: "#9ece6a"
    yellow: "#e0af68"
    blue: "#7aa2f7"
    magenta: "#ad8ee6"
    cyan: "#449dab"
    white: "#787c99"
  bright:
    black: "#444b6a"
    red: "#ff7a93"
    green: "#b9f27c"
    yellow: "#ff9364"
    blue: "#7da6ff"
    magenta: "#bb9af7"
    cyan: "#0db9d7"
    white: "#acb0d0"



cursor:
  style:
    shape: Block
    blinking: off
    blink-interval: 750

selection:
  save_to_clipboards: true

live_config_reload: true

shell:
  program: /usr/bin/bash

# key_bindings:
#   -{ key: Return, mods: Super|Shift, action: SpawnNewInstance }
